# Generated by Django 3.1.7 on 2021-03-12 01:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='Категория')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Картинка')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IpAdress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='ip пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Наименование')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Привествующая картинка\n(высота = 320px)')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата публикации')),
                ('body', ckeditor.fields.RichTextField(null=True, verbose_name='Содержание статьи')),
                ('view', models.IntegerField(default=0, null=True, verbose_name='Кол-во просмотров')),
                ('autor', models.TextField(null=True, verbose_name='Автор публикации')),
                ('ip', models.GenericIPAddressField(verbose_name='IP пользователей')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='TopPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.post', verbose_name='Одна из лучших статей')),
            ],
        ),
    ]
